changelog:
  categories:
    - title: Features
      labels:
        - feature
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - docs
    - title: Other
      labels:
        - "*"
